python sub_catal.py  55 1  > wiki_table_Hall_SDSS.txt
python sub_catal.py  76  2   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  112  3   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  118  4   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  165  5   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  176  6   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  179  7   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  205  8   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  212  9   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  218  10   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  255  11   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  259  12   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  303  13   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  354  14   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  415  15   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  507  16   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  559  17   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  567  18   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  619  19   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  647  20   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  732  21   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  772  22   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  798  23   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  832  24   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  937  25   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1051  26   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1056  27   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1106  28   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1158  29   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1170  30   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1301  31   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1413  32   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1461  33   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1472  34   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1478  35   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1520  36   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1524  37   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1577  38   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1594  39   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1621  40   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1713  41   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1781  42   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1909  43   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1921  44   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1927  45   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  1933  46   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  2003  47   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  2268  48   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  2316  49   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  2479  50   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  2615  51   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  2680  52   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  2768  53   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  2769  54   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  2784  55   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  2889  56   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  2905  57   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  3072  58   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  3076  59   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  3397  60   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  3440  61   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  3563  62   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  3569  63   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  3667  64   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  3764  65   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  3912  66   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  3914  67   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  4116  68   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  4398  69   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  4511  70   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  4539  71   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  4585  72   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  4916  73   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  4921  74   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  4979  75   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  5198  76   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  5270  77   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  5411  78   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  5527  79   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  5645  80   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  5792  81   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  6193  82   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  6208  83   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  6263  84   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  6302  85   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  6309  86   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  6318  87   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  6335  88   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  6528  89   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  6546  90   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  6627  91   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  6628  92   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  6636  93   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  6687  94   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  6848  95   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  6982  96   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  7042  97   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  7096  98   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  7114  99   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  7246  100   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  7366  101   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  7465  102   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  7478  103   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  7533  104   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  7556  105   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  7653  106   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  7775  107   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  7800  108   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  7819  109   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  7966  110   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  8165  111   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  8173  112   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  8205  113   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  8232  114   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  8235  115   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  8245  116   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  8281  117   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  8293  118   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  8318  119   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  8571  120   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  8624  121   >> wiki_table_Hall_SDSS.txt
python sub_catal.py  9033  122   >> wiki_table_Hall_SDSS.txt
